### ISSUE TITLE
Can t access to the RSS feed build in Raspbian rpi4 32bits

### ISSUE THREAD

**Issue by Zoz92** [Guisch/yggfetch#1]
Maybe can u add ur image to dockerhub ?

Logs:     
RSS Server running

Incomming request for /

Launching headless browser...

(node:1) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!

/home/node/yggfetch/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: 22: /home/node/yggfetch/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: Syntax error: "(" unexpected

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/node/yggfetch/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)

    at Interface.helper_1.helper.addEventListener (/home/node/yggfetch/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)

    at Interface.emit (events.js:203:15)

    at Interface.close (readline.js:397:8)

    at Socket.onend (readline.js:173:10)

    at Socket.emit (events.js:203:15)

    at endReadableNT (_stream_readable.js:1145:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Guisch** [comment]
Hey, sorry but Puppeteer does not support ARM processor :/
See https://github.com/puppeteer/puppeteer/issues/550

**Comment by Zoz92** [comment]
thx for the reply @Guisch
