### ISSUE TITLE
Error: No node found for selector: input[name='id']

### ISSUE THREAD

**Issue by gdlx** [Guisch/yggfetch#2]
I gave it a try with Jackett but the test fails with the following error log:
```
RSS Server running
Incomming request for /engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=seed
Launching headless browser...
Logging with creddentials
Waiting for Cloudflare challenge
(node:1) UnhandledPromiseRejectionWarning: Error: No node found for selector: input[name='id']
    at Object.assert (/home/node/yggfetch/node_modules/puppeteer/lib/helper.js:29:15)
    at DOMWorld.type (/home/node/yggfetch/node_modules/puppeteer/lib/DOMWorld.js:291:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/node/yggfetch/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.type (/home/node/yggfetch/node_modules/puppeteer/lib/Page.js:793:33)
    at puppeteer.launch.then (/home/node/yggfetch/index.js:46:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Guisch** [comment]
Hey, indeed sometimes the headless browser require a bit more time for the login modal to show up. I've added a condition that should fix the issue on the last commit.
Feel free to reopen if you still experience the same issue.
